---
title       : Resting Metabolic Rate (RMR) Calculator
subtitle    : 
author      : BoonFei
job         : 
framework   : revealjs        
highlighter : highlight.js  
hitheme     : tomorrow     
widgets     : []        
mode        : selfcontained
revealjs:
  theme: simple

--- .custom

# Resting Metabolic Rate (RMR) Calculator


--- .custom

## What is RMR?

Your BMR (Basal Metabolic Rate) is an estimate of how many calories you'd burn if you were to do nothing but rest for 24 hours. It represents the minimum amount of energy needed to keep your body functioning, including breathing and keeping your heart beating.

Your BMR does not include the calories you burn from normal daily activities or exercise.
 

--- &custom .custom

## WHAT DETERMINES RESTING METABOLIC RATE?

A very small number of people have physical conditions that give them strange resting metabolic rates.

However, for the vast majority of people, resting metabolic rate can be calculated knowing a few key variables. They are age, sex, weight, height, and fat-free body mass. Fat-free mass is a very important variable. Weight and height are used in one formula to determine body surface area.


--- .custom

## THINGS THAT AFFECT YOUR METABOLIC RATE

MUSCLE: More muscle increases your RMR.

AGE: Your RMR decreases with age.

GENETICS: A decrease in your RMR can be due to genetics.

THE WEATHER: Living in a cold enviroment can increase your RMR. I know this sounds strange, but you expend more energy while moving around in cold weather. It's a lot easier to move around in summer but more of an effort to "get going" in winter.

MEALS: Small regular meals will increase your RMR.

PREGNANCY: It can increase your RMR.

CRASH-DIETING: It will decrease your RMR.

SUPPLEMENTS: Some supplements can raise your RMR.

--- .custom

## Project Submission

- shinyapps.io ([shinny apps](https://boonfeicoursera.shinyapps.io/shiny-app/))
-  I make it after watching this [Coursera Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1) 






